const fs = require('fs');
const HexLuthor = require('./src/hex-luthor');

console.log('Building HEX Luthor distribution...\n');

// Generate minified version
const src = fs.readFileSync('./src/hex-luthor.js', 'utf8');
const minified = src
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/\/\/.*$/gm, '')
  .replace(/\n\s*/g, ' ')
  .replace(/\s{2,}/g, ' ')
  .trim();

fs.writeFileSync('./dist/hex-luthor.min.js', minified);
console.log('✅ dist/hex-luthor.min.js');

// Generate pattern preview gallery
const previews = HexLuthor.preview(['#0d1117', '#21262d']);
const galleryHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HEX Luthor Pattern Gallery</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { 
      background: #0d1117; 
      color: #c9d1d9; 
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif;
      line-height: 1.6;
    }
    .hero { 
      text-align: center; 
      padding: 4rem 2rem; 
      background: linear-gradient(180deg, #161b22 0%, #0d1117 100%);
      border-bottom: 1px solid #30363d;
    }
    .hero h1 { font-size: 3rem; margin-bottom: 0.5rem; color: #f0f6fc; }
    .hero p { font-size: 1.2rem; color: #8b949e; }
    .grid { 
      display: grid; 
      grid-template-columns: repeat(auto-fill, minmax(350px, 1fr)); 
      gap: 1.5rem; 
      padding: 2rem; 
      max-width: 1400px; 
      margin: 0 auto;
    }
    .card { 
      background: #161b22; 
      border-radius: 12px; 
      overflow: hidden; 
      border: 1px solid #30363d;
      transition: transform 0.2s, border-color 0.2s;
    }
    .card:hover { transform: translateY(-4px); border-color: #58a6ff; }
    .card .preview { 
      width: 100%; 
      height: 200px; 
      display: block; 
      border: none;
      object-fit: cover;
    }
    .card .info { padding: 1.25rem; }
    .card .name { 
      font-size: 1.1rem; 
      font-weight: 600; 
      color: #f0f6fc; 
      margin-bottom: 0.5rem;
      font-family: 'SF Mono', Monaco, monospace;
    }
    .card .code { 
      background: #0d1117; 
      padding: 0.75rem; 
      border-radius: 6px; 
      font-family: 'SF Mono', Monaco, monospace;
      font-size: 0.85rem;
      color: #7ee787;
      overflow-x: auto;
      border: 1px solid #30363d;
    }
    .footer {
      text-align: center;
      padding: 3rem;
      color: #8b949e;
      border-top: 1px solid #30363d;
    }
    .footer a { color: #58a6ff; text-decoration: none; }
  </style>
</head>
<body>
  <div class="hero">
    <img src="assets/logo-original.png" width="100" alt="HEX Luthor Logo" style="margin-bottom: 0.5rem;"><br><h1>⚡ HEX Luthor</h1>
    <p>Seamless, borderless background patterns for GitHub</p>
  </div>
  <div class="grid">
    ${previews.map(p => `
    <div class="card">
      <img class="preview" src="${p.dataUri}" alt="${p.type} pattern" loading="lazy">
      <div class="info">
        <div class="name">${p.type}</div>
        <div class="code">hex-luthor readme -p ${p.type} -c "#0d1117,#21262d"</div>
      </div>
    </div>
    `).join('')}
  </div>
  <div class="footer">
    <p>Generated by <a href="https://github.com/hex-luthor/hex-luthor">HEX Luthor</a> • MIT License</p>
  </div>
</body>
</html>`;

fs.writeFileSync('./dist/gallery.html', galleryHtml);
console.log('✅ dist/gallery.html');

console.log('\n🎉 Build complete!');
